initial re-commit

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -1,49 +1,39 @@
-#
-# Learn more about this Gitpod configuration file in the documentation at https://www.gitpod.io/docs/configuration
-#
+image: nberlette/gitpod-enhanced:latest
+
 ports:
   - port: 3000
     onOpen: open-preview
 
-# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks
 tasks:
-  - init: npm install
-    command: |
-      (
-        RED='\033[0;31m'
-        BOLD='\033[1;30m'
-        NC='\033[0m' # No Color
+  - init: |
+      pnpm install --global prisma 
+      brew install supabase/tap/supabase
 
+    command: |
+      ( 
+        RED='\033[0;31m'; BOLD='\033[1;30m'; NC='\033[0m';
         gp env | grep --quiet VITE_SUPABASE_URL
-        if [ $? -eq 1 ]
-        then
-          printf "${RED}Missing environment variables for supabase.${NC}\n\n"
-          printf "To configure them:\n\n1. run: ${BOLD}gp env -e VITE_SUPABASE_URL=your_supabase_url VITE_SUPABASE_ANON_KEY=your_supabase_anon_key${NC}\n2. stop and re-start your workspace\n"
+        if [ $? -gt 0 ]; then
+          printf "${RED}Missing environment variables for supabase!${NC}\n\n"
+          printf "To configure them:\n\n1. ${BOLD}gp env -e VITE_SUPABASE_URL={url} VITE_SUPABASE_ANON_KEY={anon_key}${NC}\n\n2. ${BOLD}gp stop${NC}\n\n3. restart your workspace\n"
         else
-          export HMR_HOST=`gp url 3000`
-          npm run dev
+          export HMR_HOST=$(gp url 3000) && pnpm run dev; 
         fi
       )
 
 github:
   prebuilds:
-    # enable for the master/default branch (defaults to true)
     master: true
-    # enable for all branches in this repo (defaults to false)
     branches: true
-    # enable for pull requests coming from this repo (defaults to true)
     pullRequests: true
-    # enable for pull requests coming from forks (defaults to false)
-    pullRequestsFromForks: true
-    # add a check to pull requests (defaults to true)
     addCheck: true
-    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
-    addComment: false
-    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
     addBadge: true
-    # add a label once the prebuild is ready to pull requests (defaults to false)
-    addLabel: false
+    addLabel: true
 
 vscode:
   extensions:
     - svelte.svelte-vscode
+    - eamodio.gitlens
+    - editorconfig.editorconfig
+    - christian-kohler.npm-intellisense
+    - christian-kohler.path-intellisense
